# -*- coding: utf-8 -*-
"""Funciones API.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eKTvz3pm1iSByLSRb3SdA2ybpHcGxcE_
"""

def get_champions():
    champions = champions(region="EUW")
    for champion in champions:
        print(champion.name, champion.id)

def extraer_campeones (lista, dicc):
  for campeon in lista:
    name_ = Champion(name = campeon, region="EUW")

    if len(name_.name) == 0:
      dicc["Nombre"].append("NS/NC")
    else:
      dicc["Nombre"].append(name_.name)

    if len(str(name_.id)) == 0:
      dicc["ID"].append("NS/NC")
    else:      
      dicc["ID"].append(name_.id) 

    if len(str(name_.info.difficulty)) == 0:
      dicc["Dificultad"].append("NS/NC")
    else:      
      dicc["Dificultad"].append(name_.info.difficulty)   

    if len(str(name_.info.attack)) == 0:
      dicc["AD"].append("NS/NC")
    else:      
      dicc["AD"].append(name_.info.attack)   

    if len(str(name_.info.defense)) == 0:
      dicc["Defensa"].append("NS/NC")
    else:      
      dicc["Defensa"].append(name_.info.defense)    

    if len(str(name_.info.magic)) == 0:
      dicc["AP"].append("NS/NC")
    else:      
      dicc["AP"].append(name_.info.magic) 

    if len(str(name_.passive.name)) == 0:
      dicc["Pasiva"].append("NS/NC")
    else:      
      dicc["Pasiva"].append(name_.passive.name)

    if len(str(name_.win_rates)) == 0:
      dicc["Win Rate"].append("NS/NC")
    else:      
      dicc["Win Rate"].append(name_.win_rates)
  
    if len(str(name_.play_rates)) == 0:
      dicc["Play Rate"].append("NS/NC")
    else:      
      dicc["Play Rate"].append(name_.play_rates)   
    
    if len(str(name_.ban_rates)) == 0:
      dicc["Ban Rate"].append("NS/NC")
    else:      
      dicc["Ban Rate"].append(name_.ban_rates)